const C = {
  ENGINE: 'JSREE APEX Enterprise V7',
  VERSION: '7.0.0',

  RECEIVER_NAME: 'JEYARAJ ALAGAR',
  RECEIVER_UPI: 'jayarajj126-3@okicici',
  ALLOWED_AMOUNTS: [120, 500, 1000, 2000, 5000],
  TIME_WINDOW_DAYS: 1,

  MAX_IMAGE_BYTES: 10 * 1024 * 1024,
  MIN_IMAGE_BYTES: 512,
  MIN_WIDTH: 200,
  MIN_HEIGHT: 200,

  OCR_TIMEOUT_MS: 45000,
  OCR_RETRIES: 2,

  TESSERACT_LANG: 'eng',
  TESSERACT_CONFIG: 1,

  PYTHON_BRIDGE_TIMEOUT_MS: 120000,
  PYTHON_BRIDGE_AVAILABLE: false,

  VOTE_WEIGHT_TESSERACT: 1,
  VOTE_WEIGHT_PADDLE: 1,
  VOTE_WEIGHT_EASYOCR: 1,
  VOTE_MIN_ENGINES: 1,

  BLUR_THRESHOLD: 100,
  BRIGHTNESS_MIN: 20,
  BRIGHTNESS_MAX: 250,
  CONTRAST_MIN: 20,
  MIN_TEXT_LENGTH: 8,

  FRAUD_SCORE_MAX: 100,
  FRAUD_HIGH_RISK_THRESHOLD: 60,
  FRAUD_MEDIUM_RISK_THRESHOLD: 30,

  DECISION_AUTO_APPROVE_MIN: 90,
  DECISION_MANUAL_REVIEW_MIN: 50,

  AMOUNT_TOLERANCE: 0.01,
  DATE_TOLERANCE_DAYS: 1,
  MAX_RAPID_SUBMISSIONS: 3,
  RAPID_WINDOW_MS: 60000,
};

module.exports = C;
