const _shared = require('../_shared.js');

module.exports = Object.freeze({
  ENGINE_VERSION: '5.0.0',

  EXPECTED_RECEIVER_UPI: _shared.ADMIN_UPI_ID,
  EXPECTED_RECEIVER_NAME: 'JEYARAJ ALAGAR',

  ALLOWED_AMOUNTS: [120, 500, 1000],

  UTR_MIN_LENGTH: 10,
  UTR_MAX_LENGTH: 45,
  TXN_ID_MIN_LENGTH: 6,
  TXN_ID_MAX_LENGTH: 50,

  MIN_IMAGE_SIZE_BYTES: 2048,
  MAX_IMAGE_SIZE_BYTES: 15 * 1024 * 1024,
  MIN_IMAGE_DIMENSION: 150,
  MAX_IMAGE_WIDTH: 6000,
  MAX_IMAGE_HEIGHT: 12000,

  TIME_WINDOW_MINUTES: 30,
  DATE_FORMAT: 'YYYY-MM-DD',

  PER_STRATEGY_TIMEOUT_MS: 4000,
  OCR_ENGINE_TIMEOUT_MS: 12000,
  FETCH_TIMEOUT_MS: 8000,
  DEDUP_TIMEOUT_MS: 5000,

  ACCEPTED_PAYMENT_STATUSES: ['SUCCESS', 'SUCCESSFUL', 'COMPLETED', 'PAID'],
  REJECTED_PAYMENT_STATUSES: ['FAILED', 'REJECTED', 'DECLINED', 'CANCELLED', 'UNSUCCESSFUL', 'REVERSED', 'EXPIRED'],

  APPROVED_STATUS: 'verified',
  REJECTED_STATUS: 'rejected',
  MANUAL_REVIEW_STATUS: 'manual_review',

  CONFIDENCE_MIN_FLOOR: 30,
  CONFIDENCE_MANUAL_REVIEW_FLOOR: 60,
  CONFIDENCE_AUTO_APPROVE: 90,

  FRAUD_THRESHOLD_LOW: 30,
  FRAUD_THRESHOLD_MEDIUM: 60,
  FRAUD_THRESHOLD_HIGH: 80,

  MIN_OCR_TEXT_LENGTH: 15,
  BLUR_SCORE_MAX: 65,
  TAMPER_SCORE_MAX: 25,
  EDGE_DENSITY_MIN: 0.01,
  MIN_TEXT_LINES: 2,

  IST_OFFSET: '+05:30',
});