module.exports = Object.freeze({
  ENGINE: 'NUCLEAR',

  ALLOWED_AMOUNTS: [120, 500, 1000],

  RECEIVER_UPI: 'jayarajj126-3@okicici',
  RECEIVER_NAME: 'JEYARAJ ALAGAR',

  TIME_WINDOW_MINUTES: 30,

  ACCEPTED_STATUSES: ['SUCCESS', 'SUCCESSFUL', 'COMPLETED', 'PAID'],

  APPROVED: 'verified',
  REJECTED: 'rejected',
  MANUAL_REVIEW: 'manual_review',

  MIN_IMAGE_BYTES: 2048,
  MAX_IMAGE_BYTES: 15728640,

  OCR_TIMEOUT_MS: 15000,
  FETCH_TIMEOUT_MS: 8000,
  DEDUP_TIMEOUT_MS: 5000,

  BUDGET_MS: 30000,
});